### ISSUE TITLE
Update the github workflow surge deployment

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-site#1492]
**Is your feature request related to a problem? Please describe.**
- PR-Preview-Generator workflow needs to be updated since the token is expired.

**Describe the solution you'd like**
- Update the [main.yml](https://github.com/sef-global/sef-site/blob/master/.github/workflows/main.yml) with the below content

```
name: PR-Preview-Generator
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Installing Surge
        run: npm i -g surge
      - name: Deploying on Surge
        env:
          DEPLOY_DOMAIN: https://pr-${{ github.event.number }}-sef-site.surge.sh
        run: surge ./ $DEPLOY_DOMAIN --token ${{ secrets.SURGE_TOKEN }}
```

**Are you working on it?**
No
